language: go

dist: bionic

env:
  global:
    - CACHE_NAME=${TRAVIS_ARCH}
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

git:
  depth: false

go:
  - "1.13.x"
  - "1.14.x"
  - master

arch:
  - amd64
  - arm64

os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - go: master
  fast_finish: true
  exclude:
    - os: windows
      go: master
    - arch: arm64
      os: osx
    - arch: arm64
      os: windows

cache:
  directories:
    - $HOME/gopath/pkg/mod
    - $HOME/.cache/go-build
    - $HOME/Library/Caches/go-build
    - $HOME/AppData/Local/go-build



before_install:
    # https://travis-ci.community/t/go-cant-find-gcc-with-go1-11-1-on-windows/293/5
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        choco install mingw -y;
        export PATH=/c/tools/mingw64/bin:"$PATH";
    fi

install:
  - mkdir -p $HOME/src
  - mv $TRAVIS_BUILD_DIR $HOME/src
  - export TRAVIS_BUILD_DIR=$HOME/src/golibsass
  - cd $HOME/src/golibsass

script:
  - go mod download || true
  - go vet ./... || true
  - go test -race ./libsass -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)