// TODO(bep)

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package libsass

/*
#cgo CFLAGS: -O2 -fPIC
#cgo CPPFLAGS: -I../libsass_src/include
#cgo CXXFLAGS: -g -std=c++0x -O2 -fPIC
#cgo LDFLAGS: -lstdc++ -lm
#cgo darwin linux LDFLAGS: -ldl
#include "stdint.h"
#include "sass/context.h"
#include <stdlib.h>
*/
import "C"
import "unsafe"

// SassEnvFrame as declared in sass/functions.h:23
type SassEnvFrame C.Sass_Env_Frame

// SassCalleeEntry as declared in sass/functions.h:25
type SassCalleeEntry C.Sass_Callee_Entry

// SassImportEntry as declared in sass/functions.h:27
type SassImportEntry C.Sass_Import_Entry

// SassImportList as declared in sass/functions.h:28
type SassImportList C.Sass_Import_List

// SassImporterEntry as declared in sass/functions.h:30
type SassImporterEntry C.Sass_Importer_Entry

// SassImporterList as declared in sass/functions.h:31
type SassImporterList C.Sass_Importer_List

// SassImporterFn type as declared in sass/functions.h:33
type SassImporterFn func(url string, cb SassImporterEntry, compiler SassCompiler) SassImportList

// SassFunctionEntry as declared in sass/functions.h:37
type SassFunctionEntry C.Sass_Function_Entry

// SassFunctionList as declared in sass/functions.h:38
type SassFunctionList C.Sass_Function_List

// SassCompiler as declared in sass/functions.h:18
type SassCompiler *C.struct_Sass_Compiler

// SassContext as declared in sass/context.h:20
type SassContext *C.struct_Sass_Context

// SassDataContext as declared in sass/context.h:22
type SassDataContext *C.struct_Sass_Data_Context

// SassFileContext as declared in sass/context.h:21
type SassFileContext *C.struct_Sass_File_Context

// SassOptions as declared in sass/functions.h:17
type SassOptions *C.struct_Sass_Options

// SassValue as declared in sass/values.h:14
const sizeofSassValue = unsafe.Sizeof(C.union_Sass_Value{})

type SassValue [sizeofSassValue]byte
